sudo: false
language: python
python:
  - 2.7
before_install:
- pip install pyopenssl ndg-httpsclient pyasn1
script: |
    nosetests \
      -v \
      --rednose \
      --with-coverage \
      --cover-erase \
      --cover-html \
      --cover-html-dir=htmlcov \
      --cover-package=grow \
      grow/
