sudo: false
language: python
python: 2.7
cache:
  pip: true
  directories:
  - "./env/"
  - "./gaenv/"

env:
- GAE_ZIP=google_appengine_1.9.36.zip

matrix:
  include:
    - os: osx
      language: generic

# https://github.com/travis-ci/travis-ci/issues/738#issuecomment-11179888
before_script:
- pip install -r requirements-dev.txt
- wget -nv https://storage.googleapis.com/appengine-sdks/featured/${GAE_ZIP}
- unzip -q ${GAE_ZIP} -d ${HOME}

script:
- make test-ci

before_deploy:
- make release-ci
- FILENAME_CI=Grow-SDK-${TRAVIS_OS_NAME/linux/Linux}-${TRAVIS_TAG}.zip
- FILENAME_CI=${FILENAME_CI/osx/Mac}

deploy:
  provider: releases
  api_key:
    secure: DXcOJEmWKTwE3vIxKTA7lOWEyoCZWkN6lYpSh+qVRgunp/ZyJgeR0BXfljYCduv+jewCQRONNnRzxAl0++KiWFm3wu/PMHKCMmdWbC5lOT/sipMkbiMCH7++MsCBUhhdOeEBguTP9P4M2q/K3Pt7zaXalE64eNpD5MCfCbqw+3o=
  draft: true
  file: ${FILENAME_CI}
  on:
    tags: true
  skip_cleanup: true
