sudo: false
language: python
python: 2.7
cache:
  pip: true
  directories:
  - ./env/
  - ./gaenv/

env:
- GAE_ZIP=google_appengine_1.9.36.zip

matrix:
  include:
    - os: osx
      language: generic

os:
- linux
- osx

# https://docs.travis-ci.com/user/multi-os/
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi

# https://github.com/travis-ci/travis-ci/issues/738#issuecomment-11179888
before_script:
- pip install -r requirements-dev.txt
- wget -nv https://storage.googleapis.com/appengine-sdks/featured/${GAE_ZIP}
- unzip -q ${GAE_ZIP} -d ${HOME}

script:
- make test-ci
